{"name": "测试登录错误", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == '账户名或密码错误'\n  - 账户名或密码错误", "trace": "username = 'admin123', password = '123456', authcode = '123456', exceptedText = '账户名或密码错误'\ninLoginModule = <pytest_cms.page.login.LoginPage object at 0x110cefcd0>\n\n    @allure.title(\"测试登录错误\")\n    @allure.description(\"所有登录错误的场景\")\n    @pytest.mark.parametrize('username, password, authcode, exceptedText',[\n        ('admin123', '123456', '123456', '账户名或密码错误'),\n        # ('admin', '123456', '123456', '系统接口请求超时')\n    ])\n    def test_login_error(username, password, authcode, exceptedText, inLoginModule: LoginPage):\n        print(\"测试登录\")\n    \n        inLoginModule.login(username, password, authcode)\n        inLoginModule.wd.implicitly_wait(10)\n    \n        propmt = inLoginModule.wd.find_element(by=By.XPATH, value=\"//p[@class='el-message__content']\")\n        inLoginModule.wd.implicitly_wait(5)\n    \n        # 判断是否登录成功\n>       assert propmt.text == exceptedText\nE       AssertionError: assert '' == '账户名或密码错误'\nE         - 账户名或密码错误\n\ntests/test_login.py:60: AssertionError"}, "description": "所有登录错误的场景", "parameters": [{"name": "username", "value": "'admin123'"}, {"name": "password", "value": "'123456'"}, {"name": "authcode", "value": "'123456'"}, {"name": "exceptedText", "value": "'账户名或密码错误'"}], "start": 1697263223357, "stop": 1697263236809, "uuid": "d3f48d6d-7374-4df4-a07f-f0869800e594", "historyId": "93385e1687a5eeddadca742e1c58a790", "testCaseId": "b9959f67a24e9ee9ac792b54473bd57b", "fullName": "tests.test_login#test_login_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "192.168.1.2"}, {"name": "thread", "value": "73140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}