{"name": "测试成功", "status": "failed", "statusDetails": {"message": "AssertionError: assert '' == '系统接口请求超时'\n  - 系统接口请求超时", "trace": "username = 'admin', password = '123456', authcode = '123456', exceptedText = '系统接口请求超时'\ninLoginModule = <pytest_cms.page.login.LoginPage object at 0x110cefcd0>\n\n    @allure.title(\"测试成功\")\n    @allure.description(\"登录成功的场景测试\")\n    @pytest.mark.parametrize('username, password, authcode, exceptedText',[\n        # ('admin123', '123456', '123456', '账户名或密码错误'),\n        ('admin', '123456', '123456', '系统接口请求超时')\n    ])\n    def test_login_success(username, password, authcode, exceptedText, inLoginModule: LoginPage):\n        print(\"测试登录\")\n    \n        inLoginModule.login(username, password, authcode)\n        inLoginModule.wd.implicitly_wait(10)\n    \n        propmt = inLoginModule.wd.find_element(by=By.XPATH, value=\"//p[@class='el-message__content']\")\n        inLoginModule.wd.implicitly_wait(5)\n    \n        # 判断是否登录成功\n>       assert propmt.text == exceptedText\nE       AssertionError: assert '' == '系统接口请求超时'\nE         - 系统接口请求超时\n\ntests/test_login.py:41: AssertionError"}, "description": "登录成功的场景测试", "parameters": [{"name": "username", "value": "'admin'"}, {"name": "password", "value": "'123456'"}, {"name": "authcode", "value": "'123456'"}, {"name": "exceptedText", "value": "'系统接口请求超时'"}], "start": 1697263209848, "stop": 1697263223297, "uuid": "48c71e2a-dd08-4732-830b-98af849d8c7a", "historyId": "169bf0fc30f7d1e5811e77a8cb763b50", "testCaseId": "86600b41e86dab7ca99f472fa61e4b05", "fullName": "tests.test_login#test_login_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "192.168.1.2"}, {"name": "thread", "value": "73140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}